package Forms;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author Gustavo Picoli
 */
public class TelaCadastro extends javax.swing.JFrame {

    
    public TelaCadastro() {
        initComponents();
        gerarAcessibilidade();
        
    }
    
    public void  gerarAcessibilidade() {
        btnSalvar.setMnemonic(KeyEvent.VK_S);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAviso = new javax.swing.ButtonGroup();
        PainelCamadas = new javax.swing.JLayeredPane();
        lblFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        lblSetor = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        lblTarefa = new javax.swing.JLabel();
        txtTarefa = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelCamadas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendamento de Tarefas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 51, 204))); // NOI18N
        PainelCamadas.setToolTipText("Agendamento de Tarefas");

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFuncionario.setLabelFor(txtFuncionario);
        lblFuncionario.setText("Funcionário");

        txtFuncionario.setToolTipText("Insira o nome do funcionário");
        txtFuncionario.setNextFocusableComponent(txtSetor);

        lblSetor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSetor.setLabelFor(txtSetor);
        lblSetor.setText("Setor");

        txtSetor.setToolTipText("Insira o setor");
        txtSetor.setNextFocusableComponent(txtTarefa);

        lblTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTarefa.setLabelFor(txtTarefa);
        lblTarefa.setText("Descrição da tarefa");

        txtTarefa.setNextFocusableComponent(txtData);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setLabelFor(txtData);
        lblData.setText("Data para entrega");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setToolTipText("");
        txtData.setNextFocusableComponent(btnSalvar);

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar(alt+S)");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblAviso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAviso.setText("Emitir aviso para funcionário?");

        buttonGroupAviso.add(jRadioButtonSim);
        jRadioButtonSim.setText("Sim");

        buttonGroupAviso.add(jRadioButtonNao);
        jRadioButtonNao.setText("Não");

        PainelCamadas.setLayer(lblFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(txtFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(lblSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(txtSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(lblTarefa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(txtTarefa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(lblData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(txtData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(btnSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(lblAviso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(jRadioButtonSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelCamadas.setLayer(jRadioButtonNao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PainelCamadasLayout = new javax.swing.GroupLayout(PainelCamadas);
        PainelCamadas.setLayout(PainelCamadasLayout);
        PainelCamadasLayout.setHorizontalGroup(
            PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamadasLayout.createSequentialGroup()
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetor)
                    .addGroup(PainelCamadasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFuncionario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCamadasLayout.createSequentialGroup()
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFuncionario)
                        .addComponent(txtSetor, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addComponent(lblTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCamadasLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSim)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonNao)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCamadasLayout.createSequentialGroup()
                        .addComponent(lblAviso)
                        .addGap(116, 116, 116))))
            .addGroup(PainelCamadasLayout.createSequentialGroup()
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        PainelCamadasLayout.setVerticalGroup(
            PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamadasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblFuncionario)
                .addGap(18, 18, 18)
                .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSetor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAviso))
                .addGap(18, 18, 18)
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarefa)
                    .addComponent(jRadioButtonSim)
                    .addComponent(jRadioButtonNao))
                .addGap(18, 18, 18)
                .addComponent(txtTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PainelCamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCamadasLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelCamadasLayout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(43, 43, 43))
        );

        jMenu.setText("Menu");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSair);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCamadas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCamadas.getAccessibleContext().setAccessibleName("Agendamento");
        PainelCamadas.getAccessibleContext().setAccessibleDescription("Formulário para agendamento de tarefas");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String op = "";
        if (jRadioButtonSim.isSelected())
        op = "Sim";
        else if (jRadioButtonNao.isSelected())
        op = "Não";
        else
        op = "não informado";

        JOptionPane.showMessageDialog(null,
            "Seu nome é " + txtFuncionario.getText()+
                    " e seu setor é "+ txtSetor.getText() + "." +
                            " \nSua tarefa é: " + txtTarefa.getText() +"." 
                                    + " \nSeu prazo de entrega é dia: " + txtData.getText() + "."
                                            + " \nEmitir aviso ao funcionário: " + op ,"Tarefa",              JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane PainelCamadas;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupAviso;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JLabel lblTarefa;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtSetor;
    private javax.swing.JTextField txtTarefa;
    // End of variables declaration//GEN-END:variables
}
